### PR TITLE
Add CI badge

### LINKED ISSUE #4: Activate travis builds for this repository
@chcorbato @gavanderhoorn could you please activate Travis-ci to build this repository?

Thanks!

### PR DESCRIPTION
**Pull request by Chamango90**
closes https://github.com/rosin-project/automatica18_scan_and_plan_demo/issues/4

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
> ipa-jfh assigned ipa-jfh and ipa-nhg and unassigned ipa-jfh and ipa-nhg 11 minutes ago
> ipa-jfh ipa-jfh requested a review from ipa-nhg 8 minutes ago

really? ;)

**Comment by Chamango90** [comment]
Haha yes a very trivial review and miss-clicked some times

**Comment by gavanderhoorn** [comment]
Would it be an idea to add license badges and support level badges as well (similar to [ros-industrial/fanuc](https://github.com/ros-industrial/fanuc))?

"Support level" may be too much ROS-I, but the license badges provide a quick way for visitors to understand the licensing of the components.

**Comment by Chamango90** [comment]
> "Support level" may be too much ROS-I, but the license badges provide a quick way for visitors to understand the licensing of the components.

Yes I agree and I included it now in the commit.

**Review by hsd-dev — APPROVED** [review]

**Pull request merged**
